# Generated by Django 5.2.1 on 2025-05-15 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacoteturistico',
            name='imagem',
            field=models.ImageField(default=1, upload_to='pacotes/'),
            preserve_default=False,
        ),
    ]
